services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-wplace:py310
    container_name: qr-wplace-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

